// <auto-generated />
namespace SARCEM_TCC.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeCheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeCheck));
        
        string IMigrationMetadata.Id
        {
            get { return "201904140138229_changeCheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
